# TODO: change ports to be in corresponding range
services:
  stock_api_zookeeper:
    container_name: stock_api_zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  stock_api_kafka:
    container_name: stock_api_kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - stock_api_zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: stock_api_zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://stock_api_kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./stock_api_kafka/start-kafka.sh:/usr/local/bin/start-kafka.sh
    command: ["bash", "/usr/local/bin/start-kafka.sh"]

  stock_api:
    container_name: stock_api
    build:
      context: ./stock_api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./stock_api:/app

  stock_api_cassandra:
    container_name: stock_api_cassandra
    build:
      context: ./stock_api_cassandra
      dockerfile: Dockerfile
    volumes:
      - cassandra_data:/var/lib/cassandra

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app


volumes:
  cassandra_data:


# services:
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    container_name: zookeeper
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 6181
#      ZOOKEEPER_TICK_TIME: 2000
#
#  kafka:
#    image: confluentinc/cp-kafka:latest
#    container_name: kafka
#    depends_on:
#      - zookeeper
#    environment:
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:6181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:6003
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    ports:
#      - "6003:6003"
#    volumes:
#      - ./matching_engine_kafka/start-kafka.sh:/usr/local/bin/start-kafka.sh
#    command: ["bash", "/usr/local/bin/start-kafka.sh"]
#
#  matching_engine_1:
#    build:
#      context: ./matching_engine
#      dockerfile: Dockerfile
#    volumes:
#      - ./matching_engine:/app
#    environment:
#      - REDIS_PORT=6379
#      - REDIS_NODE=redis1
#    depends_on:
#      - redis1
#      - kafka
#      - postgres
##
##  matching_engine_2:
##    build:
##      context: ./matching_engine
##      dockerfile: Dockerfile
##    volumes:
##      - ./matching_engine:/app
##    environment:
##      - REDIS_PORT=6380
##      - REDIS_NODE=redis2
##    depends_on:
##      - redis2
##      - kafka
##
##  matching_engine_3:
##    build:
##      context: ./matching_engine
##      dockerfile: Dockerfile
##    volumes:
##      - ./matching_engine:/app
##    environment:
##      - REDIS_PORT=6381
##      - REDIS_NODE=redis3
##    depends_on:
##      - redis3
##      - kafka
#
#  redis1:
#    image: redis
#    ports:
#      - 6379:6381
##
##  redis2:
##    image: redis
##    ports:
##      - 6380:6381
##
##  redis3:
##    image: redis
##    ports:
##      - 6381:6381
#
#  postgres:
#    build: ./matching_engine_postgres/
#    ports:
#      - "6432:6432"
